### ISSUE TITLE
Update to babel6?

### ISSUE THREAD

**Issue by goatslacker** [insin/react-heatpack#18]

**Comment by insin** [comment]
[react-hot-loader](https://github.com/gaearon/react-hot-loader) is deprecated and [react-transform](https://github.com/gaearon/babel-plugin-react-transform/issues/46) doesn't work on Babel 6 yet, plus I haven't figured out how to use react-transform for heatpack (#9) because Babel is in charge of requiring it and its dependencies, not webpack.
